live_config_reload: true

env:
  TERM: xterm-256color

window:
  opacity: 0.95
  decorations: full
  padding:
    x: 5
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty

draw_bold_text_with_bright_colors: true

# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '0x1e2127'
    foreground: '0xabb2bf'

  # Normal colors
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'

# Visual bell
bell:
  animation: EaseOutExpo
  duration: 0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  faux_scrolling_lines: 1
  hide_when_typing: false

font:
  normal:
    family: RobotoMono Nerd Font
    style: Regular

  bold:
    family: RobotoMono Nerd Font

  italic:
    family: RobotoMono Nerd Font

  size: 12

key_bindings:
  - { key: V,     mods: Control,        action: Paste             }
  - { key: C,     mods: Control,        action: Copy              }
  - { key: C,     mods: Alt,            chars: "\x03"             }
  - { key: Q,     mods: Control,        action: Quit              }
  - { key: N,     mods: Control,        action: SpawnNewInstance  }
  - { key: Left,  mods: Control,        chars: "\x1bb"            } # one word left
  - { key: Right, mods: Control,        chars: "\x1bf"            } # one word right
