export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export BREW_PREFIX=$(brew --prefix)

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

export MAVEN_OPTS="-Xmx2048m"

# Use gnu-bins installed with brew instead of OSX defaults
DIRS=(`brew --prefix`/opt/*/libexec/gnubin)
for dir in "${DIRS[@]}"
do
  PATH=$dir:$PATH
done
export PATH="/usr/local/opt/maven@3.5/bin:$PATH:/usr/local/sbin"

# Add man pages for gnu-bins
MANS=(`brew --prefix`/opt/*/libexec/gnuman)
for man in "${MANS[@]}"
do
  MANPATH=$man:$MANPATH
done
export MANPATH="/usr/local/man:$MANPATH"

export TERM="xterm-256color"

export HISTORY_IGNORE="(history|ls|l|la|ll|lla|lsa|cd|cd *|pwd|exit|* --help|man *|cls|clear)"

export EDITOR=/usr/local/bin/nano

# disable oh my zsh auto updates
export DISABLE_AUTO_UPDATE="true"

export DOTFILES_DIRECTORY="${HOME}/git/dotfiles"
export ZSH_CUSTOM=${DOTFILES_DIRECTORY}/zshCustom

export STARSHIP_CONFIG=~/.starship

export AUTOENV_FILE_ENTER=.autoenv.zsh
export AUTOENV_FILE_LEAVE=.autoenv.zsh
