
### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk

zinit light mroth/evalcache

_evalcache dircolors -b
autoload -U colors && colors

# theme
setopt promptsubst
zinit ice from"gh-r" as"command" atload'!_evalcache starship init zsh'
zinit light starship/starship

zinit light ${ZSH_CUSTOM}/plugins/aliases
zinit light ${ZSH_CUSTOM}/plugins/functions

zinit as"program" make'!' atclone'./direnv hook zsh > zhook.zsh' \
    atpull'%atclone' pick"direnv" src"zhook.zsh" for \
        direnv/direnv

zinit wait lucid for \
  ${ZSH_CUSTOM}/plugins/bindkey \
  ${ZSH_CUSTOM}/plugins/completions \
  ${ZSH_CUSTOM}/plugins/opts \
  ${ZSH_CUSTOM}/plugins/java \
  OMZL::completion.zsh \
  OMZL::compfix.zsh \
  OMZL::history.zsh \
  OMZL::spectrum.zsh \
  OMZP::colored-man-pages \
  as"completion" \
    OMZP::docker/_docker \
  as"completion" \
    OMZP::docker-compose/_docker-compose \
  OMZP::gradle \
  atload"unalias mvn! mvnag mvnboot mvnc mvncd mvnce mvnci mvncie mvncini mvncist mvncisto mvncom mvncp mvnct mvncv mvncvst mvnd mvndocs mvndt mvne mvnfmt mvnjetty mvnp mvnqdev mvns mvnsrc mvnt mvntc mvntc7 mvn-updates" \
    OMZP::mvn \
  blockf \
    zsh-users/zsh-history-substring-search \
  caarlos0/zsh-open-pr \
  voronkovich/gitignore.plugin.zsh \
  blockf \
    as"completion" \
      zsh-users/zsh-completions \
  zpm-zsh/clipboard \
  mattmc3/zsh-safe-rm \
  as"program" pick"bin/git-dsf" \
    zdharma/zsh-diff-so-fancy \
  ${ZSH_CUSTOM}/plugins/colors \
  Tarrasch/zsh-autoenv

# this must be the last loaded
zinit wait lucid for \
  atinit"ZINIT[COMPINIT_OPTS]='-i' zpcompinit; zpcdreplay" \
    zdharma/fast-syntax-highlighting

# iterm2 integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# load zmv
autoload -U add-zsh-hook zmv
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion