#!/bin/bash

FONTS_DIR="${HOME}/Library/Fonts"
NEW_FONTS_DIR="${RESOURCES_DIRECTORY}/fonts"

function copy_fonts(){
  TARGET="$1"
  DEST="$2"

  for fonts in "${TARGET}"/*; do
    cp "${fonts}" "${DEST}"
  done
}

function install_fonts(){
  run 'copying fonts'
  copy_fonts "${NEW_FONTS_DIR}" "${FONTS_DIR}"
}

function backup_fonts(){
  run 'backup fonts'
  copy_fonts "${FONTS_DIR}" "${NEW_FONTS_DIR}"
}
