#!/bin/bash

[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && . "$(brew --prefix)/opt/nvm/nvm.sh"
NPM_PACKAGES="${RESOURCES_DIRECTORY}/npm/default-packages"
NVM_HOME="$HOME/.nvm"

function install_node_and_packages(){
  if [ ! -d "$NVM_HOME" ]; then
    mkdir -p "$NVM_HOME"
    link "${NPM_PACKAGES}" "${NVM_HOME}/${file}"
  fi
  nvm install node

  nvm install 8.11.1
  nvm use 8.11.1
  npm install -g gulp-cli
  nvm alias old_player 8.11.1

  nvm install 10.15.0
  nvm alias player 10.15.0

  nvm use default
}

function backup_npm_packages(){
  run "backup npm packages"
  CURRENT="$(nvm current)"
  nvm use default
  npm ls -g --depth=0 --json=true | jq -r '.dependencies | keys[] |  select(. != "npm")' > "${NPM_PACKAGES}"
  nvm use $CURRENT
}
