#!/bin/bash

function setup_squid() {
  run "copy squid conf"
  cp "${RESOURCES_DIRECTORY}/squid/squid.conf" "/usr/local/etc"

  run "create squid log directories"
  mkdir -p "/usr/local/var/logs/squid"
}

function backup_squid() {
  run "backup squid conf"
  cp "/usr/local/etc/squid.conf" "${RESOURCES_DIRECTORY}/squid"
}
