#!/bin/bash

SUBLIME_SUPPORT_DIR="${HOME}/Library/Application Support/Sublime Text 3"
SUBLIME_INSTALLED_PACKAGES_DIR="${SUBLIME_SUPPORT_DIR}/Installed Packages"
SUBLIME_USER_DIR="${SUBLIME_SUPPORT_DIR}/Packages/User"
SUBLIME_PKG_DIR="${RESOURCES_DIRECTORY}/sublime/packages"
SUBLIME_SETTINGS_DIR="${RESOURCES_DIRECTORY}/sublime/settings"

function copy_sublime_files(){
  TARGET="$1"
  DEST="$2"

  for file in "${TARGET}"/*; do
    cp -r "${file}" "${DEST}"
  done
}

function create_sublime_dir(){
  DIR=$1
  if [ ! -d "$DIR" ]; then
    mkdir -p "${DIR}"
  fi
}

function create_sublime_directories(){
  create_sublime_dir "${SUBLIME_INSTALLED_PACKAGES_DIR}"
  create_sublime_dir "${SUBLIME_USER_DIR}"
}

function copy_sublime_settings(){
  copy_sublime_files "${SUBLIME_SETTINGS_DIR}" "${SUBLIME_USER_DIR}"
}

function copy_sublime_packages(){
   copy_sublime_files "${SUBLIME_PKG_DIR}" "${SUBLIME_INSTALLED_PACKAGES_DIR}"
}

function backup_sublime_settings(){
  copy_sublime_files "${SUBLIME_USER_DIR}" "${SUBLIME_SETTINGS_DIR}"
}

function backup_sublime_packages(){
  copy_sublime_files "${SUBLIME_INSTALLED_PACKAGES_DIR}" "${SUBLIME_PKG_DIR}"
}

function setup_sublime(){
  run "install"
  brew install --cask sublime-text

  run "creating packages and settings directories"
  create_sublime_directories

  run "copy settings"
  copy_sublime_settings

  run "copy packages"
  copy_sublime_packages
}

function bakup_sublime(){
  run "backup sublime settings"
  backup_sublime_settings

  run "backup sublime packages"
  backup_sublime_packages
}
